-- Update remaining PATA kit descriptions (lines 104-165)
UPDATE pata_kits SET description = 'Temporary Work Stoppage/Slowdown' WHERE code = 'PATA 302';
UPDATE pata_kits SET description = 'Flagger Relocation - Walking' WHERE code = 'PATA 302';
UPDATE pata_kits SET description = 'Flagger Relocation - Riding in Work Vehicle' WHERE code = 'PATA 302';
UPDATE pata_kits SET description = 'Flagger Relocation - Riding in Pilot Vehicle' WHERE code = 'PATA 302';
UPDATE pata_kits SET description = 'Workers Remain in Vehicles Throughout Operation' WHERE code = 'PATA 303';
UPDATE pata_kits SET description = 'Work in Right Lane - Undivided Highway' WHERE code = 'PATA 304-A';
UPDATE pata_kits SET description = 'Work in Left Lane - Undivided Highway' WHERE code = 'PATA 304-B';
UPDATE pata_kits SET description = 'Work in Right Lane - Divided Highway' WHERE code = 'PATA 305-A';
UPDATE pata_kits SET description = 'Work in Left Lane - Divided Highway' WHERE code = 'PATA 305-B';
UPDATE pata_kits SET description = 'Work in Right Lane of 3 Lane Approach' WHERE code = 'PATA 306-A';
UPDATE pata_kits SET description = 'Work in Left Lane of 3 Lane Approach' WHERE code = 'PATA 306-B';
UPDATE pata_kits SET description = 'Work in Center Lane of 3 Lane Approach' WHERE code = 'PATA 306-C';
UPDATE pata_kits SET description = 'Mowing Where Tractor Utilizes the Roadway to Perform Operations' WHERE code = 'PATA 307';
UPDATE pata_kits SET description = 'Work on Right Side' WHERE code = 'PATA 401-A';
UPDATE pata_kits SET description = 'Work on Left Side' WHERE code = 'PATA 401-B';
UPDATE pata_kits SET description = 'Work in Right Lane' WHERE code = 'PATA 402-A';
UPDATE pata_kits SET description = 'Work in Left Lane' WHERE code = 'PATA 402-B';
UPDATE pata_kits SET description = 'Work in All Lanes Requiring a Rolling Slow Down or Stoppage' WHERE code = 'PATA 408';
UPDATE pata_kits SET description = 'Work in Right and Center Lanes' WHERE code = 'PATA 403-A';
UPDATE pata_kits SET description = 'Work in Left and Center Lanes' WHERE code = 'PATA 403-B';
UPDATE pata_kits SET description = 'Work in Right Lane Near Right-Exit Ramp' WHERE code = 'PATA 404-A';
UPDATE pata_kits SET description = 'Work in Left Lane Near Left-Exit Ramp' WHERE code = 'PATA 404-B';
UPDATE pata_kits SET description = 'Work in Right Lane Near Right-Entrance Ramp with YIELD Control' WHERE code = 'PATA 405-A';
UPDATE pata_kits SET description = 'Work in Left Lane Near Left-Entrance Ramp with YIELD Control' WHERE code = 'PATA 405-B';
UPDATE pata_kits SET description = 'Work in Right Lane Near Right-Entrance Ramp with STOP Control' WHERE code = 'PATA 406-A';
UPDATE pata_kits SET description = 'Work in Left Lane Near Left-Entrance Ramp with STOP Control' WHERE code = 'PATA 406-B';
UPDATE pata_kits SET description = 'Work on Ramp Shoulder (May Have Roadway Encroachment)' WHERE code = 'PATA 407';
UPDATE pata_kits SET description = 'Work Closes All Lanes - All Traffic Must Use Right-Exit' WHERE code = 'PATA 409-A';
UPDATE pata_kits SET description = 'Work Closes All Lanes - All Traffic Must Use Left-Exit' WHERE code = 'PATA 409-B';
UPDATE pata_kits SET description = 'Work on Right Side' WHERE code = 'PATA 501-A';
UPDATE pata_kits SET description = 'Work on Left Side' WHERE code = 'PATA 501-B';
UPDATE pata_kits SET description = 'Work on Right Shoulder' WHERE code = 'PATA 502-A';
UPDATE pata_kits SET description = 'Work on Left Shoulder' WHERE code = 'PATA 502-B';
UPDATE pata_kits SET description = 'Work in Right Lane' WHERE code = 'PATA 503-A';
UPDATE pata_kits SET description = 'Work in Left Lane' WHERE code = 'PATA 503-B';
UPDATE pata_kits SET description = 'Two Lanes Shift Utilizing Left Shoulder' WHERE code = 'PATA 508-A';
UPDATE pata_kits SET description = 'Two Lanes Shift Utilizing Right Shoulder' WHERE code = 'PATA 508-B';
UPDATE pata_kits SET description = 'Work in Right and Center Lanes' WHERE code = 'PATA 504-A';
UPDATE pata_kits SET description = 'Work in Left and Center Lanes' WHERE code = 'PATA 504-B';
UPDATE pata_kits SET description = 'Work in Right Lane Near Right-Exit Ramp' WHERE code = 'PATA 505-A';
UPDATE pata_kits SET description = 'Work in Left Lane Near Left-Exit Ramp' WHERE code = 'PATA 505-B';
UPDATE pata_kits SET description = 'Work in Right Lane Near Right-Entrance Ramp with YIELD Control' WHERE code = 'PATA 506-A';
UPDATE pata_kits SET description = 'Work in Left Lane Near Left-Entrance Ramp with YIELD Control' WHERE code = 'PATA 506-B';
UPDATE pata_kits SET description = 'Work in Right Lane Near Right-Entrance Ramp with STOP Control' WHERE code = 'PATA 507-A';
UPDATE pata_kits SET description = 'Work in Left Lane Near Left-Entrance Ramp with STOP Control' WHERE code = 'PATA 507-B';
UPDATE pata_kits SET description = 'Work on Right or Left Side' WHERE code = 'PATA 601';
UPDATE pata_kits SET description = 'Mowing (Tractor Remains on or Beyond Shoulder)' WHERE code = 'PATA 604';
UPDATE pata_kits SET description = 'Work in Right Lane' WHERE code = 'PATA 602-A';
UPDATE pata_kits SET description = 'Work in Left Lane' WHERE code = 'PATA 602-B';
UPDATE pata_kits SET description = 'Work in Right Lane' WHERE code = 'PATA 603-A';
UPDATE pata_kits SET description = 'Work in Left Lane' WHERE code = 'PATA 603-B';
UPDATE pata_kits SET description = 'Work in Two Lanes (Right & Center or Left & Center)' WHERE code = 'PATA 603-C';
UPDATE pata_kits SET description = 'Pedestal-Mounted Signals' WHERE code = 'PATA 701';
UPDATE pata_kits SET description = 'Trailer-Mounted Signals' WHERE code = 'PATA 702';
UPDATE pata_kits SET description = 'Pedestal-Mounted Signals - Complex Conditions' WHERE code = 'PATA 703';
UPDATE pata_kits SET description = 'Trailer-Mounted Signals - Complex Conditions' WHERE code = 'PATA 704';
UPDATE pata_kits SET description = 'Overhead Signals on Fixed Supports with Span Wire' WHERE code = 'PATA 705';
UPDATE pata_kits SET description = 'Trailer-Mounted Signals - Long-Term Operation' WHERE code = 'PATA 706';
UPDATE pata_kits SET description = 'Two-Lane, Two-Way Conventional Highways' WHERE code = 'PATA 801';
UPDATE pata_kits SET description = 'Multi-Lane Highways Where Passing is Allowed' WHERE code = 'PATA 802';
UPDATE pata_kits SET description = 'Multi-Lane Highways Where Passing is Prohibited' WHERE code = 'PATA 803';
UPDATE pata_kits SET description = 'Highways with Three Lanes in One Direction' WHERE code = 'PATA 804';
