-- Complete PATA Kit Contents from pata-list.xlsx - ALL 160+ ENTRIES
-- This script loads all PATA kits (101-A through 805) with their sign requirements

-- Lines 2-30 (PATA 101-A through 127-B) - Already covered, but including for completeness
-- PATA 101-A through 127-B (lines 2-30)
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 501-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 501-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 501-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 501-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-A', 'W21-5', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-A', 'W21-5BR', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-B', 'W21-5', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-B', 'W21-5BL', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 502-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-A', 'W20-5R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-A', 'W4-2R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-B', 'W20-5L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-B', 'W4-2L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 503-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-A', 'W5-5', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-A', 'W1-4BL', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-A', 'W1-4BR', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-B', 'W5-5', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-B', 'W1-4BL', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-B', 'W1-4BR', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 508-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-A', 'W20-5AR', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-A', 'W4-2R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-B', 'W20-5AL', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-B', 'W4-2L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 504-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-A', 'W20-5R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-A', 'W4-2R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-A', 'W25-4', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-B', 'W20-5L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-B', 'W4-2L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 505-B', 'W25-4', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'W20-5R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'W4-2R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'W4-1R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'W3-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'R1-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-A', 'R4-9', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'W20-5L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'W4-2L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'W4-1L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'W3-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'R1-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 506-B', 'R4-9', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'W20-5R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'W4-2R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'W4-1R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'W3-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'R1-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-A', 'R4-9', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'W20-5L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'W4-2L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'W4-1L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'W3-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'R1-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 507-B', 'R4-9', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 601', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 604', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 604', 'W21-14', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 604', 'G80-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 604', 'V1-6-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 602-A', 'W20-5R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 602-B', 'W20-5L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 603-A', 'W20-5R', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 603-B', 'W20-5L', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 603-C', 'W9-3', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 701', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 701', 'W20-4', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 701', 'W3-3', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 701', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 701', 'R10-6AL', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 702', 'W20-1', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 702', 'W20-4', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 702', 'W3-3', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 702', 'G20-2', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 702', 'R10-6AL', 1);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 703', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 704', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 705', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 706', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 801', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 802', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 803', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 804', '(no signs)', 0);
INSERT INTO pata_kit_contents (pata_kit_code, sign_designation, quantity) VALUES ('PATA 805', '(no signs)', 0);
