-- Clear existing descriptions and reload all PTS and PATA kit descriptions

-- PTS Kit Descriptions (based on pts-list.xlsx)
UPDATE pts_kits SET description = 'Milled or Binder Pavement Differential in Right Lane' WHERE code = 'PTS 001A';
UPDATE pts_kits SET description = 'Milled or Binder Pavement Differential in Left Lane' WHERE code = 'PTS 001B';
UPDATE pts_kits SET description = 'Milled or Binder Pavement Differential in Right and Center Lanes' WHERE code = 'PTS 002A';
UPDATE pts_kits SET description = 'Milled or Binder Pavement Differential in Left and Center Lanes' WHERE code = 'PTS 002B';
UPDATE pts_kits SET description = 'Pavement Differential on Right Shoulder' WHERE code = 'PTS 3';
UPDATE pts_kits SET description = 'Pavement Differential in Median Shoulder' WHERE code = 'PTS 4';
UPDATE pts_kits SET description = 'WZSSC Stationary Shoulder Closure with Channelizing Devices' WHERE code = 'PTS 12';
UPDATE pts_kits SET description = 'WZSSC Lane Closure with Channelizing Devices' WHERE code = 'PTS 13';
UPDATE pts_kits SET description = 'WZSSC Stationary Shoulder Closure with Temporary Barrier' WHERE code = 'PTS 14';
UPDATE pts_kits SET description = 'Mobile Shoulder Operations' WHERE code = 'PTS 910-2';
UPDATE pts_kits SET description = 'Mowing / Litter Cleanup Operations' WHERE code = 'PTS 910-7';
UPDATE pts_kits SET description = 'Stationary Shoulder Closure with Channelizing Devices' WHERE code = 'PTS 920-2';
UPDATE pts_kits SET description = 'Single Lane Closure with Channelizing Devices' WHERE code = 'PTS 920-3';
UPDATE pts_kits SET description = 'Dual Lane Closure with Channelizing Devices' WHERE code = 'PTS 920-4';
UPDATE pts_kits SET description = 'Right Lane Closure within Transition from 2 to 3 Lanes' WHERE code = 'PTS 920-5';
UPDATE pts_kits SET description = 'Center / Right Lane Closure within Transition from 2 to 3 Lanes' WHERE code = 'PTS 920-6';
UPDATE pts_kits SET description = 'Lane Closure Traffic Pattern for Interchange and Service Plaza Areas with' WHERE code = 'PTS 920-7A';
UPDATE pts_kits SET description = 'Lane Closure Traffic Pattern for Interchange and Service Plaza Areas with' WHERE code = 'PTS 920-7B';
UPDATE pts_kits SET description = 'Multiple Single Lane Closure Traffic Patterns' WHERE code = 'PTS 920-8';
UPDATE pts_kits SET description = 'Multiple Dual Lane Closure Traffic Patterns' WHERE code = 'PTS 920-9';
UPDATE pts_kits SET description = 'Utility Work Along Shoulder' WHERE code = 'PTS 920-15';
UPDATE pts_kits SET description = 'Stationary Shoulder Closure with Channelizing Devices' WHERE code = 'PTS 930-2';
UPDATE pts_kits SET description = 'Single Lane Closure with Channelizing Devices' WHERE code = 'PTS 930-3';
UPDATE pts_kits SET description = 'Dual Lane Closure with Channelizing Devices' WHERE code = 'PTS 930-4';
UPDATE pts_kits SET description = 'Right Lane Closure within Transition from 2 to 3 Lanes' WHERE code = 'PTS 930-5';
UPDATE pts_kits SET description = 'Center / Right Lane Closure within Transition from 2 to 3 Lanes' WHERE code = 'PTS 930-6';
UPDATE pts_kits SET description = 'Lane Closure Traffic Pattern for Interchange and Service Plaza Areas with' WHERE code = 'PTS 930-7A';
UPDATE pts_kits SET description = 'Lane Closure Traffic Pattern for Interchange and Service Plaza Areas with' WHERE code = 'PTS 930-7B';
UPDATE pts_kits SET description = 'Multiple Single Lane Closure Traffic Patterns' WHERE code = 'PTS 930-8';
UPDATE pts_kits SET description = 'Multiple Dual Lane Closure Traffic Patterns' WHERE code = 'PTS 930-9';
UPDATE pts_kits SET description = 'Stationary Shoulder Closure with Temporary Barrier' WHERE code = 'PTS 930-14A';
UPDATE pts_kits SET description = 'Multiple Stationary Shoulder Closures with Temporary Barrier' WHERE code = 'PTS 930-14B';
UPDATE pts_kits SET description = 'Single Lane Closure with Temporary Barrier' WHERE code = 'PTS 930-15';
UPDATE pts_kits SET description = 'Lanes Shift Detail - 2 Lanes Shift - Left' WHERE code = 'PTS 930-16A';
UPDATE pts_kits SET description = 'Lanes Shift Detail - 2 Lanes Shift - Right' WHERE code = 'PTS 930-16B';
UPDATE pts_kits SET description = 'Lanes Shift Detail - 3 Lanes Shift - Left' WHERE code = 'PTS 930-17A';
UPDATE pts_kits SET description = 'Lanes Shift Detail - 3 Lanes Shift - Right' WHERE code = 'PTS 930-17B';
UPDATE pts_kits SET description = 'Crossover Traffic Pattern' WHERE code = 'PTS 930-18';
UPDATE pts_kits SET description = 'Emergency Pull-Off - Type I in Temporary Barrier' WHERE code = 'PTS 930-19A';
UPDATE pts_kits SET description = 'Emergency Pull-Off - Type III' WHERE code = 'PTS 930-19B';
UPDATE pts_kits SET description = 'Opening in Temporary Barrier for Access to Construction Area' WHERE code = 'PTS 930-20';
UPDATE pts_kits SET description = 'Combined Emergency Pull-Off - Type I and Opening in Temporary Barrier for' WHERE code = 'PTS 930-21';
UPDATE pts_kits SET description = 'Access to Construction Area without Barrier' WHERE code = 'PTS 930-22';
UPDATE pts_kits SET description = 'Opening in Temporary Barrier with Truck Crossing' WHERE code = 'PTS 930-23';
UPDATE pts_kits SET description = 'Toll Plaza Right Lane Closure Operations Less Than 8 Hours' WHERE code = 'PTS 940-2';
UPDATE pts_kits SET description = 'Toll Plaza Right Lane Closure Operations Between 8 and 72 Hours' WHERE code = 'PTS 940-3';
UPDATE pts_kits SET description = 'Toll Plaza Right Lane Closure Operations More Than 72 Hours' WHERE code = 'PTS 940-4';
UPDATE pts_kits SET description = 'Toll Plaza Center Lane Closure Operations Less Than 8 Hours' WHERE code = 'PTS 940-5';
UPDATE pts_kits SET description = 'Toll Plaza Center Lane Closure Operations Between 8 and 72 Hours' WHERE code = 'PTS 940-6';
UPDATE pts_kits SET description = 'Toll Plaza Center Lane Closure Operations More Than 72 Hours' WHERE code = 'PTS 940-7';
UPDATE pts_kits SET description = 'Advance Warning Signs for Work on Ramps' WHERE code = 'PTS 940-8';
UPDATE pts_kits SET description = 'Service Plaza Area Construction' WHERE code = 'PTS 940-9';
UPDATE pts_kits SET description = 'Stationary Shoulder Closure on Ramp with Channelizing Devices' WHERE code = 'PTS 940-11A';
UPDATE pts_kits SET description = 'Lane Narrows on Ramp with Channelizing Devices' WHERE code = 'PTS 940-11B';
UPDATE pts_kits SET description = 'Stationary Shoulder Closure on Ramp with Temporary Barrier' WHERE code = 'PTS 940-12A';
UPDATE pts_kits SET description = 'Lane Narrows on Ramp with Temporary Barrier' WHERE code = 'PTS 940-12B';
UPDATE pts_kits SET description = 'Single Lane Closure with Channelizing Devices for Dual Lane Ramp' WHERE code = 'PTS 940-13A';
UPDATE pts_kits SET description = 'Single Lane Closure with Temporary Barrier for Dual Lane Ramp' WHERE code = 'PTS 940-13B';
UPDATE pts_kits SET description = 'Slip Ramp - Lane Addition Closure with Channelizing Devices' WHERE code = 'PTS 940-14A';
UPDATE pts_kits SET description = 'Slip Ramp - Lane Closure with Channelizing Devices' WHERE code = 'PTS 940-14B';
UPDATE pts_kits SET description = 'Traffic Line Painting Operation for Single Lane Interchange Ramps' WHERE code = 'PTS 940-15A';

-- PATA Kit Descriptions (based on pata-list.xlsx) - First 60 entries
UPDATE pata_kits SET description = 'Single-Lane Approach - No Roadway Encroachment' WHERE code = 'PATA 101-A';
UPDATE pata_kits SET description = 'Multi-Lane Approach - Right Shoulder Work - No Roadway Encroachment' WHERE code = 'PATA 101-B';
UPDATE pata_kits SET description = 'Multi-Lane Approach - Left Shoulder Work - No Roadway Encroachment' WHERE code = 'PATA 101-C';
UPDATE pata_kits SET description = 'Single-Lane Approach - Shoulder Work With Minor Roadway Encroachment' WHERE code = 'PATA 102';
UPDATE pata_kits SET description = 'Single Lane Approach - Shoulder Work With Major Roadway Encroachment' WHERE code = 'PATA 103';
UPDATE pata_kits SET description = 'Work Space on Roadway Center Line' WHERE code = 'PATA 104';
UPDATE pata_kits SET description = 'Work Space in the Center of an Intersection' WHERE code = 'PATA 105';
UPDATE pata_kits SET description = 'Work in Single-Lane and Center Line - Two Flaggers' WHERE code = 'PATA 106';
UPDATE pata_kits SET description = 'Work in One-Lane - Two Flaggers' WHERE code = 'PATA 107';
UPDATE pata_kits SET description = 'Work in Single-Lane - One Flagger' WHERE code = 'PATA 108';
UPDATE pata_kits SET description = 'Self-Regulating Stop Control' WHERE code = 'PATA 111';
UPDATE pata_kits SET description = 'Work in One-Lane with Pilot Vehicle - Two Flaggers' WHERE code = 'PATA 117';
UPDATE pata_kits SET description = 'Self-Regulating Lane Shift into Opposing Lane' WHERE code = 'PATA 118';
UPDATE pata_kits SET description = 'Work in Adjacent Lanes with Opposing Traffic - Two Flaggers' WHERE code = 'PATA 120';
UPDATE pata_kits SET description = 'Self-Regulating Lane Shift into Center Left-Turn Lane' WHERE code = 'PATA 121';
UPDATE pata_kits SET description = 'Work in Center Left-Turn Lane' WHERE code = 'PATA 122';
UPDATE pata_kits SET description = 'Work within One Quadrant of a Roundabout' WHERE code = 'PATA 131';
UPDATE pata_kits SET description = 'Work on One Leg Entering a Roundabout' WHERE code = 'PATA 132';
UPDATE pata_kits SET description = 'Work on One Leg Exiting a Roundabout' WHERE code = 'PATA 133';
UPDATE pata_kits SET description = 'Work in Two Lanes, Same Direction - Two Flaggers' WHERE code = 'PATA 119';
UPDATE pata_kits SET description = 'Work in Right Lane - Undivided Highway' WHERE code = 'PATA 123-A';
UPDATE pata_kits SET description = 'Work in Left Lane - Undivided Highway' WHERE code = 'PATA 123-B';
UPDATE pata_kits SET description = 'Work in Two Lanes, Same Direction (Lane Shift into Opposing Lane)' WHERE code = 'PATA 124';
UPDATE pata_kits SET description = 'Work in Right Lane - Divided Highway' WHERE code = 'PATA 125-A';
UPDATE pata_kits SET description = 'Work in Left Lane - Divided Highway' WHERE code = 'PATA 125-B';
UPDATE pata_kits SET description = 'Work in Right Lane and on Lane Line' WHERE code = 'PATA 126-A';
UPDATE pata_kits SET description = 'Work in Left Lane and on Lane Line' WHERE code = 'PATA 126-B';
UPDATE pata_kits SET description = 'Work in Right Two Lanes (Lane Shift into Adjacent Lane)' WHERE code = 'PATA 127-A';
UPDATE pata_kits SET description = 'Work in Left Two Lanes (Lane Shift into Adjacent Lane)' WHERE code = 'PATA 127-B';
UPDATE pata_kits SET description = 'Standard Orange Detour Signs' WHERE code = 'PATA 116-A';
UPDATE pata_kits SET description = 'Red Arrow Detour Signs (ADT <1500)' WHERE code = 'PATA 116-B';
UPDATE pata_kits SET description = 'Sidewalk Closed with Pedestrian Detour' WHERE code = 'PATA 128';
UPDATE pata_kits SET description = 'Sidewalk Closed with Pedestrian Diversion' WHERE code = 'PATA 129';
UPDATE pata_kits SET description = 'Sidewalk and Crosswalk Closure with Pedestrian Detour' WHERE code = 'PATA 130';
UPDATE pata_kits SET description = 'Approaching a Stop Sign - Two Flaggers' WHERE code = 'PATA 109-A';
UPDATE pata_kits SET description = 'Approaching a Stop Sign - Three Flaggers' WHERE code = 'PATA 109-B';
UPDATE pata_kits SET description = 'Approaching All-way Stop - Two Flaggers' WHERE code = 'PATA 109-C';
UPDATE pata_kits SET description = 'Approaching All-way Stop - Three Flaggers' WHERE code = 'PATA 109-D';
UPDATE pata_kits SET description = 'Approaching Traffic Signal - Two Flaggers' WHERE code = 'PATA 109-E';
UPDATE pata_kits SET description = 'Approaching Traffic Signal - Three Flaggers' WHERE code = 'PATA 109-F';
UPDATE pata_kits SET description = 'Departing the Intersection - Two Flaggers' WHERE code = 'PATA 109-G';
UPDATE pata_kits SET description = 'Departing the Intersection - Three Flaggers' WHERE code = 'PATA 109-H';
UPDATE pata_kits SET description = 'Departing an All-way Stop - Two Flaggers' WHERE code = 'PATA 109-I';
UPDATE pata_kits SET description = 'Departing an All-way Stop - Three Flaggers' WHERE code = 'PATA 109-J';
UPDATE pata_kits SET description = 'Departing a Traffic Signal - Two Flaggers' WHERE code = 'PATA 109-K';
UPDATE pata_kits SET description = 'Departing a Traffic Signal - Three Flaggers' WHERE code = 'PATA 109-L';
UPDATE pata_kits SET description = 'Approaching an Intersection with Stop Signs on Side Roads - Two Flaggers' WHERE code = 'PATA 110-A';
UPDATE pata_kits SET description = 'Approaching an Intersection with Stop Signs on Side Roads - Four Flaggers' WHERE code = 'PATA 110-B';
UPDATE pata_kits SET description = 'Approaching an Intersection with Uncontrolled Side Roads - Two Flaggers' WHERE code = 'PATA 110-C';
UPDATE pata_kits SET description = 'Approaching an Intersection with Uncontrolled Side Roads - Four Flaggers' WHERE code = 'PATA 110-D';
UPDATE pata_kits SET description = 'Approaching an All-Way Stop Intersection - Two Flaggers' WHERE code = 'PATA 110-E';
UPDATE pata_kits SET description = 'Approaching an All-Way Stop Intersection - Four Flaggers' WHERE code = 'PATA 110-F';
UPDATE pata_kits SET description = 'Approaching a Yellow Flashing Traffic Signal - Two Flaggers' WHERE code = 'PATA 110-G';
UPDATE pata_kits SET description = 'Approaching a Yellow Flashing Traffic Signal - Four Flaggers' WHERE code = 'PATA 110-H';
UPDATE pata_kits SET description = 'Approaching a Red Flashing Traffic Signal - Two Flaggers' WHERE code = 'PATA 110-I';
UPDATE pata_kits SET description = 'Approaching a Red Flashing Traffic Signal - Four Flaggers' WHERE code = 'PATA 110-J';
UPDATE pata_kits SET description = 'Departing an Intersection with Stop Signs on Side Roads - Two Flaggers' WHERE code = 'PATA 110-K';
UPDATE pata_kits SET description = 'Departing an Intersection with Stop Signs on Side Roads - Four Flaggers' WHERE code = 'PATA 110-L';
UPDATE pata_kits SET description = 'Departing an Intersection with Uncontrolled Side Roads - Two Flaggers' WHERE code = 'PATA 110-M';
UPDATE pata_kits SET description = 'Departing an Intersection with Uncontrolled Side Roads - Four Flaggers' WHERE code = 'PATA 110-N';
UPDATE pata_kits SET description = 'Departing an All-Way Stop Intersection - Two Flaggers' WHERE code = 'PATA 110-O';
UPDATE pata_kits SET description = 'Departing an All-Way Stop Intersection - Four Flaggers' WHERE code = 'PATA 110-P';
UPDATE pata_kits SET description = 'Departing a Yellow Flashing Traffic Signal - Two Flaggers' WHERE code = 'PATA 110-Q';
UPDATE pata_kits SET description = 'Departing a Yellow Flashing Traffic Signal - Four Flaggers' WHERE code = 'PATA 110-R';
UPDATE pata_kits SET description = 'Departing a Red Flashing Traffic Signal - Two Flaggers' WHERE code = 'PATA 110-S';
UPDATE pata_kits SET description = 'Departing a Red Flashing Traffic Signal - Four Flaggers' WHERE code = 'PATA 110-T';
UPDATE pata_kits SET description = 'Flagger on Closed Lane Approach, AFAD at Other End' WHERE code = 'PATA 112';
UPDATE pata_kits SET description = 'AFAD on Closed Lane Approach, Flagger at Other End' WHERE code = 'PATA 113';
UPDATE pata_kits SET description = 'AFADs with Two Operators' WHERE code = 'PATA 114';
UPDATE pata_kits SET description = 'AFADs with One Operator' WHERE code = 'PATA 115';
UPDATE pata_kits SET description = 'Single-Lane Approach' WHERE code = 'PATA 201-A';
UPDATE pata_kits SET description = 'Multi-Lane Approach - Right Shoulder' WHERE code = 'PATA 201-B';
UPDATE pata_kits SET description = 'Multi-Lane Approach - Left Shoulder' WHERE code = 'PATA 201-C';
UPDATE pata_kits SET description = 'Single-Lane Approach' WHERE code = 'PATA 202-A';
UPDATE pata_kits SET description = 'Multi-Lane Approach - Right Shoulder' WHERE code = 'PATA 202-B';
UPDATE pata_kits SET description = 'Multi-Lane Approach - Left Shoulder' WHERE code = 'PATA 202-C';
UPDATE pata_kits SET description = 'Single-Lane Approach With Roadway Encroachment' WHERE code = 'PATA 203';
UPDATE pata_kits SET description = 'Work Space in Center of Roadway' WHERE code = 'PATA 204';
UPDATE pata_kits SET description = 'Self-Regulating Stop Control' WHERE code = 'PATA 205';
UPDATE pata_kits SET description = 'Lane Shift into Opposing Lane' WHERE code = 'PATA 206';
UPDATE pata_kits SET description = 'Lane Shift into Center Left-Turn Lane' WHERE code = 'PATA 207';
UPDATE pata_kits SET description = 'Work in Center Left-Turn Lane' WHERE code = 'PATA 208';
UPDATE pata_kits SET description = 'Work in Right Lane' WHERE code = 'PATA 209-A';
UPDATE pata_kits SET description = 'Work in Left Lane' WHERE code = 'PATA 209-B';
UPDATE pata_kits SET description = 'Work in Two Lanes, Same Direction (Lane Shift Into Opposing Lane)' WHERE code = 'PATA 210';
UPDATE pata_kits SET description = 'Work in Right Lane of One-Way Roadway' WHERE code = 'PATA 211-A';
UPDATE pata_kits SET description = 'Work in Left Lane of One-Way Roadway' WHERE code = 'PATA 211-B';
UPDATE pata_kits SET description = 'Work in Right Lane with Left Lane Encroachment - Shoulder Used as Lane' WHERE code = 'PATA 212-A';
UPDATE pata_kits SET description = 'Work in Left Lane with Right Lane Encroachment - Shoulder Used as Lane' WHERE code = 'PATA 212-B';
UPDATE pata_kits SET description = 'Work in Right Two Lanes' WHERE code = 'PATA 213-A';
UPDATE pata_kits SET description = 'Work in Left Two Lanes' WHERE code = 'PATA 213-B';
UPDATE pata_kits SET description = 'Detour of a Numbered Traffic Route' WHERE code = 'PATA 214';
UPDATE pata_kits SET description = 'Detour of a Quadrant Route' WHERE code = 'PATA 215';
UPDATE pata_kits SET description = 'Sidewalk Closed with Pedestrian Detour' WHERE code = 'PATA 216';
UPDATE pata_kits SET description = 'Sidewalk Closed with Pedestrian Diversion' WHERE code = 'PATA 217';
UPDATE pata_kits SET description = 'Sidewalk and Crosswalk Closure with Pedestrian Detour' WHERE code = 'PATA 218';
UPDATE pata_kits SET description = 'Crosswalk Closure with Pedestrian Detour' WHERE code = 'PATA 219';
UPDATE pata_kits SET description = 'Single-Lane Approach' WHERE code = 'PATA 301-A';
UPDATE pata_kits SET description = 'Multi-Lane One-Way Approach - Right Shoulder' WHERE code = 'PATA 301-B';
UPDATE pata_kits SET description = 'Multi-Lane Approach - Left Shoulder' WHERE code = 'PATA 301-C';
UPDATE pata_kits SET description = 'Mowing Where Tractor Remains on or Beyond Shoulder' WHERE code = 'PATA 307';
UPDATE pata_kits SET description = 'Two-Lane, Two-Way Approach - Mobile Flagging' WHERE code = 'PATA 302';
